with open("c:/Users/user/Documents/projects/SmartAttendance/activity_log.md", "a", encoding="utf-8") as f:
    f.write("\n\n---\n\n### [2026-06-13 17:30] — Camera Auto-Exposure, Wi-Fi Connection Wait & Telegram ID Sync\n\n")
    f.write("- **Category:** Camera / Sync / Database / Backend\n")
    f.write("- **Altered Files:**\n")
    f.write("  - `main/camera/camera_driver.c` (modified)\n")
    f.write("  - `main/database/db_manager.c` / `db_manager.h` (modified)\n")
    f.write("  - `main/network/cloud_sync.c` (modified)\n")
    f.write("  - `main/main.c` (modified)\n")
    f.write("  - `telegram_bot/bot.py` (modified)\n")
    f.write("- **Status:** \u2705 Completed\n")
    f.write("- **Log:**\n")
    f.write("  * **Software Auto-Exposure Control:** Implemented software auto-exposure inside `camera_driver.c`. By subscribing to the ESP32-P4 ISP's AE environment detector statistics callback, the driver calculates average luminance and adjusts camera exposure values and gain in a software feedback loop every 10 frames to normalize image brightness in different lighting conditions.\n")
    f.write("  * **Wi-Fi Connection Wait in Sync:** Updated `network_sync_task` in `main.c` to actively wait for Wi-Fi connection establishment (up to 30 seconds) after triggering a connect, ensuring the device doesn't attempt cloud sync before a valid IP address is obtained.\n")
    f.write("  * **Immediate Sync on Boot:** Set the touch menu event bit on system boot to trigger the network sync task immediately, syncing schedules and logs right after startup.\n")
    f.write("  * **Telegram ID Mapping Sync:** Extended `/api/sync_users` in `bot.py` to return the linked Telegram ID mapping for all users. The device-side sync routine in `cloud_sync.c` reads this mapping and invokes `db_update_user_telegram_id()` to store the linked Telegram IDs locally in SQLite, completing the lecturer and student Telegram pairing loop.\n")
print("Appended successfully!")
